/**
 * ================================================================================================
 * 🚀 JEMER ACADEMY PLATFORMS CORE ENGINE — MASTER ROOT SYSTEM LAYOUT (CRASH-PROOF V4.6 FIXED)
 * ================================================================================================
 * Description: Ultimate top-level document container shell handling global provider bounds.
 * Patch Notes: Moved the Next.js managed Script component inside the body element wrapper.
 * This completely eliminates the React 19 DOM nesting and hydration order console errors
 * while retaining your strict core configuration variables exactly as originally built.
 * Location: Saved strictly inside src/app/layout.js
 * ================================================================================================
 */

// Injects the global Tailwind CSS v4 stylesheet directives across all application screens
import './globals.css';

// Pulls down our universal display theme state context provider wrapper block from the context category
import { ThemeProvider } from '@/jemer-components/context/ThemeContext.jsx';

// Injects Next.js's official managed script controller to wrap browser script insertions safely
import Script from 'next/script';

/**
 * [SEO & BROWSER APPLICATION METADATA SCHEMAS]
 * Central configuration object mapping application page descriptors used straight by web crawlers.
 */
export const metadata = {
  title: 'Jemer Academy Core Learning Dashboard', // Title tag mapped to the browser window header bar
  description: 'High-velocity educational AI platform dashboard ecosystem.', // Core descriptive index summary
};

/**
 * [STANDALONE VIEWPORT COMPILATION SPECIFICATIONS]
 * Establishes absolute scaling boundaries to enforce responsive rendering flow layout alignment across monitors.
 */
export const viewport = {
  width: 'device-width', // Binds viewport scale width metrics directly to real hardware boundaries
  initialScale: 1.0,     // Configures base initial scale coordinates on first launch
  maximumScale: 5.0,     // Prevents radical zooming layout breakage to protect design metrics
};

/**
 * [ANTI-FLASH HARDWARE INTERCEPTOR SCRIPT]
 * Pure string-embedded blocking JavaScript tracking preference tokens instantly on the client browser.
 * Executes BEFORE Next.js compiles or paints any component layout pixel to completely 
 * eliminate jarring light-mode flashes inside dark study rooms.
 */
const antiFlashScript = `
  (function() {
    try {
      var savedMode = localStorage.getItem('jemer_theme_mode');
      var userPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      if (savedMode === 'dark' || (!savedMode && userPrefersDark)) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    } catch (e) {}
  })();
`;

/**
 * Global Master Root Shell Component Layout Handler
 * @param {Object} props - Structural properties argument dictionary supplied by Next.js compilers.
 * @param {React.ReactNode} props.children - Nested child component layouts or page views streaming through sub-routes.
 */
export default function RootLayout({ children }) {
  return (
    // 🏛️ ARCHITECTURE ANCHOR: Added suppressHydrationWarning={true}
    // This tells React's reconciliation loop to ignore the intentional class discrepancies 
    // generated by the pre-load anti-flash execution script, wiping out the console warning.
    <html 
      lang="en" 
      className="h-full bg-slate-50 transition-colors duration-200" // Sets application foundational dimensions and shifts
      suppressHydrationWarning={true} // Silences attribute delta warnings during immediate pre-load theme class assignments
    >
      
      {/* Document Header Metadata Injection Junction — Kept empty to satisfy standard HTML children specs */}
      <head />

      {/* Document body shell container spanning full viewport bounds — Governs basic antialiasing, text rendering rules, and layout themes */}
      <body className="h-full antialiased font-sans text-slate-900 bg-slate-50 dark:bg-slate-950 dark:text-slate-100 selection:bg-blue-900 selection:text-white transition-colors duration-200">
        
        {/* FIXED UPGRADE: Positioned the Next.js managed <Script /> component as the absolute first child element inside the body.
            This satisfies the React 19/Next.js 16 DOM hierarchy perfectly (preventing scripts from acting as direct children of <html>), 
            while keeping the 'beforeInteractive' strategy executing before hydration scripts load. */}
        <Script
          id="jemer-theme-anti-flash"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: antiFlashScript }}
        />

        {/* UNIVERSAL SYSTEM WRAPPER CONTAINER BOUNDARY — Distributes global user theme parameters down to atomic sub-components */}
        <ThemeProvider>
          
          {/* Renders your dashboard layout sub-routes, components, and feature pages cleanly */}
          {children}
          
        </ThemeProvider>
        
      </body>
    </html>
  );
}